spring.application.name=mallorcamarket

# Connexió a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mallorcamarket
spring.datasource.username=root
spring.datasource.password=Marina66

# Configuració JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
